# syntax=docker/dockerfile:1

##
## Build 
##
FROM golang:1.18-buster AS build

WORKDIR /app

COPY go.mod ./
COPY go.sum ./
RUN go mod download

COPY . ./
RUN go build -o /api-endpoint

EXPOSE 3001
CMD ["/api-endpoint" ]
##
## Deploy
##
# FROM gcr.io/distroless/static-debian11
# ENV GIN_MODE=release
# WORKDIR /

# COPY --from=build  /api-endpoint /bin/api-endpoint

